# Generated by Django 4.0.6 on 2022-07-13 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adresses.address'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),

        migrations.AddField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(),
            preserve_default=False,
        ),
    ]
