# Generated by Django 4.0.6 on 2022-07-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='complementet',
            new_name='complement',
        ),
    ]
