# Generated by Django 4.0.6 on 2022-07-14 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_critic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user_criticized',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critics', to=settings.AUTH_USER_MODEL),
        ),
    ]
